name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show files
        run: |
          echo "Repository files:"
          ls -la

      - name: Deploy website to Nginx
        run: |
          rsync -av --delete \
            --exclude '.git/' \
            --exclude '.github/' \
            ./ /var/www/html/

      - name: Deployment completed
        run: |
          echo "Website deployed successfully"
          ls -la /var/www/html/